### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by vdegenne** [stevenhuyn/plakait-frontend#1]
https://github.com/stevenhuyn/plakait-frontend/blob/bdd36b2c94a39df753f19ae7647881cd5c6af6ce/src/components/index.ts#L4

Shouldn't it be "Importing"? :eyes:

**Comment by stevenhuyn** [comment]
oops missed this

true yeah this should be importing

**Comment by vdegenne** [comment]
@stehyn   great game :) I really had fun playing that and it for sure drawn a smile on my face.
